name: CI

on:
  release:
    types:
      - created
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test cargo-bump
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
      - name: Run cargo-bump
        uses: ./
        with:
          working-directory: test-package
